import { HydratedDocument, Model, Schema, Types, model } from 'mongoose';

// Catalogo minimo de eventos de M02 (cuentas y seguridad). Se amplia cuando
// otro modulo (M31 completo) necesite registrar los suyos.
export const ACCIONES_AUDITORIA = [
  'LOGIN_EXITOSO',
  'LOGIN_FALLIDO',
  'USUARIO_CREADO',
  'USUARIO_ACTUALIZADO',
  'USUARIO_ESTADO_CAMBIADO',
  'USUARIO_ELIMINADO',
  'USUARIO_ELIMINACION_BLOQUEADA',
  'PASSWORD_RESETEADA',
  'PASSWORD_CAMBIADA',
  'SESIONES_CERRADAS',
  'USUARIOS_IMPORTADOS',
  // M04: Admisiones y matriculas
  'MATRICULA_CREADA',
  'MATRICULA_ESTADO_CAMBIADO',
  'MATRICULA_GRUPO_CAMBIADO',
  'MATRICULA_SOBRECUPO_AUTORIZADO',
  'DOCUMENTO_CARGADO',
  'DOCUMENTO_REVISADO',
  // M05: Año lectivo, periodos y calendario
  'ANIO_LECTIVO_CREADO',
  'ANIO_LECTIVO_ACTUALIZADO',
  'ANIO_LECTIVO_ACTIVADO',
  'ANIO_LECTIVO_CERRADO',
  'PERIODO_ESTADO_CAMBIADO',
  'BLOQUEO_PERIODO_GRUPO_ACTUALIZADO',
  'PRORROGA_OTORGADA',
  'PRORROGA_REVOCADA',
  'CALENDARIO_ACTUALIZADO',
  'ESCALA_EVALUACION_ACTUALIZADA',
  'PONDERACION_COMPONENTES_ACTUALIZADA',
  // M10: Espacios fisicos
  'ESPACIO_CREADO',
  'ESPACIO_ACTUALIZADO',
  'ESPACIO_ESTADO_CAMBIADO',
  'ESPACIO_ELIMINADO',
  'GRUPO_EXCEDE_AFORO_AULA',
  'GRUPO_AULA_ACTUALIZADA',
  // M01/M05: estructura de tiempo de las jornadas
  'JORNADA_HORARIO_ACTUALIZADO',
  'PLANTILLA_FRANJAS_ACTUALIZADA',
  // M08: Asignacion docente
  'ASIGNACION_DOCENTE_CREADA',
  'ASIGNACION_DOCENTE_ELIMINADA',
  'ASIGNACION_DOCENTE_REEMPLAZADA',
  'LIMITES_CARGA_DOCENTE_ACTUALIZADOS',
  'LIMITES_HORAS_PLAN_ACTUALIZADOS',
  // M03: Estudiantes y acudientes
  'ACUDIENTE_VINCULADO',
  'ACUDIENTE_VINCULO_ACTUALIZADO',
  'ACUDIENTE_DESVINCULADO',
  'ACUDIENTE_ACTUALIZADO',
  'ACUDIENTE_ESTADO_CAMBIADO',
  'ACUDIENTE_PORTAL_HABILITADO',
  // M06: Plan de estudios (catalogo de areas/asignaturas y configuracion curricular)
  'AREA_CREADA',
  'AREA_ACTUALIZADA',
  'AREA_ESTADO_CAMBIADO',
  'ASIGNATURA_CREADA',
  'ASIGNATURA_ACTUALIZADA',
  'ASIGNATURA_ESTADO_CAMBIADO',
  'PLAN_ASIGNATURAS_GRADO_ACTUALIZADO',
  'PLAN_EVALUACION_AREA_ACTUALIZADA',
  'PLAN_DISTRIBUCION_GRUPO_ACTUALIZADA',
  'PLAN_CREADO_DESDE_ANIO_ANTERIOR',
  // M07: Banco de referentes curriculares y desarrollo curricular
  'REFERENTE_CURRICULAR_CREADO',
  'DESARROLLO_CURRICULAR_GUARDADO',
  'DESARROLLO_CURRICULAR_ENVIADO_REVISION',
  'DESARROLLO_CURRICULAR_REVISADO',
  'DESARROLLO_CURRICULAR_REABIERTO',
  // M13: Asistencia
  'ESTADO_ASISTENCIA_CREADO',
  'ESTADO_ASISTENCIA_ACTUALIZADO',
  'ESTADO_ASISTENCIA_CAMBIADO',
  'ASISTENCIA_REGISTRADA',
  'JUSTIFICACION_ASISTENCIA_CREADA',
  'JUSTIFICACION_ASISTENCIA_REVISADA',
  // M14/M15: Convivencia. Se audita también la LECTURA (datos de menores); las de escritura se agregan con cada fase.
  'CONVIVENCIA_HISTORIAL_CONSULTADO',
  'CONVIVENCIA_CASO_CONSULTADO',
  'CONVIVENCIA_OBSERVACIONES_PROPIAS_CONSULTADAS',
  'OBSERVACION_REGISTRADA',
  'OBSERVACION_ENMENDADA',
  'OBSERVACION_ANULADA',
  'FALTA_REGISTRADA',
  'SEGUIMIENTO_OBSERVACION_REGISTRADO',
  'COMPROMISO_OBSERVACION_CERRADO',
  'CITACION_OBSERVACION_REGISTRADA',
  'SOLICITUD_CASO_REGISTRADA',
  'SOLICITUD_CASO_DESCARTADA',
  'CONVIVENCIA_BANDEJA_CONSULTADA',
  'CATALOGO_CONVIVENCIA_CREADO',
  'CATALOGO_CONVIVENCIA_ACTUALIZADO',
  'CATALOGO_CONVIVENCIA_ESTADO_CAMBIADO',
  'CATALOGO_CONVIVENCIA_ELIMINADO',
  'CONFIGURACION_CONVIVENCIA_ACTUALIZADA',
  'CASO_CONVIVENCIA_ABIERTO',
  'CASO_CONVIVENCIA_ACTUALIZADO',
  'CASO_CONVIVENCIA_ESTADO_CAMBIADO',
  'CASO_CONVIVENCIA_RECLASIFICADO',
  'CASO_CONVIVENCIA_CERRADO',
  'CASO_CONVIVENCIA_REABIERTO',
  'CASO_CONVIVENCIA_ANULADO',
  'CASO_CONVIVENCIA_IMPEDIMENTO',
  'PROTOCOLO_CONVIVENCIA_ACTUALIZADO',
  'MIEMBRO_COMITE_CREADO',
  'MIEMBRO_COMITE_ACTUALIZADO',
  'MIEMBRO_COMITE_ELIMINADO',
  'SESION_COMITE_CREADA',
  'SESION_COMITE_ACTUALIZADA',
  'SESION_COMITE_ANULADA',
  'ACTA_COMITE_FIRMADA',
  'ACTA_COMITE_ANEXO',
  'ACTA_COMITE_PDF_GENERADO',
  'IMPORTACION_CONVIVENCIA',
  'RETENCION_REPORTE_CONSULTADO',
] as const;
export type AccionAuditoria = (typeof ACCIONES_AUDITORIA)[number];

export interface IAuditLog {
  usuario_id: Types.ObjectId | null;
  accion: AccionAuditoria;
  entidad: string;
  entidad_id: Types.ObjectId | null;
  detalle: string | null;
  ip: string | null;
  createdAt: Date;
}

export type AuditLogDocument = HydratedDocument<IAuditLog>;
type AuditLogModel = Model<IAuditLog>;

const auditLogSchema = new Schema<IAuditLog, AuditLogModel>(
  {
    usuario_id: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    accion: { type: String, enum: ACCIONES_AUDITORIA, required: true },
    entidad: { type: String, required: true },
    entidad_id: { type: Schema.Types.ObjectId, default: null },
    detalle: { type: String, default: null },
    ip: { type: String, default: null },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

auditLogSchema.index({ usuario_id: 1, createdAt: -1 });
auditLogSchema.index({ accion: 1, createdAt: -1 });

export const AuditLog = model<IAuditLog, AuditLogModel>('AuditLog', auditLogSchema);
export default AuditLog;
